export const LANGUAGES = {
    hi: {
        code: 'hi',
        name: 'Hindi',
        nativeName: 'हिंदी',
        emoji: '🇮🇳',
    },
    ta: {
        code: 'ta',
        name: 'Tamil',
        nativeName: 'தமிழ்',
        emoji: '🇮🇳',
    },
    bn: {
        code: 'bn',
        name: 'Bengali',
        nativeName: 'বাংলা',
        emoji: '🇮🇳',
    },
    te: {
        code: 'te',
        name: 'Telugu',
        nativeName: 'తెలుగు',
        emoji: '🇮🇳',
    },
    mr: {
        code: 'mr',
        name: 'Marathi',
        nativeName: 'मराठी',
        emoji: '🇮🇳',
    },
    gu: {
        code: 'gu',
        name: 'Gujarati',
        nativeName: 'ગુજરાતી',
        emoji: '🇮🇳',
    },
    en: {
        code: 'en',
        name: 'English',
        nativeName: 'English',
        emoji: '🇬🇧',
    },
};

export const TRANSLATIONS = {
    hi: {
        welcomeBack: 'स्वागत है',
        selectLanguage: 'अपनी भाषा चुनें',
        speakInYourLanguage: 'अपनी भाषा में बोलें',
        continue: 'जारी रखें',
        vendor: 'विक्रेता',
        buyer: 'खरीदार',
        listCommodity: 'वस्तु सूची',
        browseMandi: 'मंडी ब्राउज़ करें',
        aiSuggestedPrice: 'एआई सुझावित मूल्य',
        whyThisPrice: 'यह मूल्य क्यों?',
        negotiate: 'बातचीत करें',
        accept: 'स्वीकार करें',
        counter: 'काउंटर ऑफर',
        marketDemand: 'बाजार मांग',
        seasonalTrends: 'मौसमी रुझान',
        nearbyMandi: 'पास की मंडी',
        commodityName: 'वस्तु का नाम',
        quantity: 'मात्रा',
        location: 'स्थान',
        bestPrice: 'सबसे अच्छी कीमत',
        voiceSearch: 'आवाज से खोजें',
    },
    ta: {
        welcomeBack: 'வணக்கம்',
        selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
        speakInYourLanguage: 'உங்கள் மொழியில் பேசுங்கள்',
        continue: 'தொடரவும்',
        vendor: 'விற்பனையாளர்',
        buyer: 'வாங்குபவர்',
        listCommodity: 'பொருள் பட்டியல்',
        browseMandi: 'சந்தையை உலாவவும்',
        aiSuggestedPrice: 'AI பரிந்துரைக்கப்பட்ட விலை',
        whyThisPrice: 'இந்த விலை ஏன?',
        negotiate: 'பேரம் பேசவும்',
        accept: 'ஏற்கவும்',
        counter: 'எதிர் சலுகை',
        marketDemand: 'சந்தை தேவை',
        seasonalTrends: 'பருவகால போக்குகள்',
        nearbyMandi: 'அருகிலுள்ள சந்தை',
        commodityName: 'பொருளின் பெயர்',
        quantity: 'அளவு',
        location: 'இடம்',
        bestPrice: 'சிறந்த விலை',
        voiceSearch: 'குரல் தேடல்',
    },
    bn: {
        welcomeBack: 'স্বাগতম',
        selectLanguage: 'আপনার ভাষা নির্বাচন করুন',
        speakInYourLanguage: 'আপনার ভাষায় কথা বলুন',
        continue: 'চালিয়ে যান',
        vendor: 'বিক্রেতা',
        buyer: 'ক্রেতা',
        listCommodity: 'পণ্য তালিকা',
        browseMandi: 'মান্ডি ব্রাউজ করুন',
        aiSuggestedPrice: 'AI প্রস্তাবিত মূল্য',
        whyThisPrice: 'এই মূল্য কেন?',
        negotiate: 'আলোচনা করুন',
        accept: 'গ্রহণ করুন',
        counter: 'কাউন্টার অফার',
        marketDemand: 'বাজার চাহিদা',
        seasonalTrends: 'মৌসুমী প্রবণতা',
        nearbyMandi: 'কাছাকাছি মান্ডি',
        commodityName: 'পণ্যের নাম',
        quantity: 'পরিমাণ',
        location: 'অবস্থান',
        bestPrice: 'সেরা মূল্য',
        voiceSearch: 'ভয়েস সার্চ',
    },
    te: {
        welcomeBack: 'స్వాగతం',
        selectLanguage: 'మీ భాషను ఎంచుకోండి',
        speakInYourLanguage: 'మీ భాషలో మాట్లాడండి',
        continue: 'కొనసాగించండి',
        vendor: 'విక్రేత',
        buyer: 'కొనుగోలుదారు',
        listCommodity: 'వస్తువు జాబితా',
        browseMandi: 'మార్కెట్ బ్రౌజ్ చేయండి',
        aiSuggestedPrice: 'AI సూచించిన ధర',
        whyThisPrice: 'ఈ ధర ఎందుకు?',
        negotiate: 'చర్చలు',
        accept: 'అంగీకరించండి',
        counter: 'కౌంటర్ ఆఫర్',
        marketDemand: 'మార్కెట్ డిమాండ్',
        seasonalTrends: 'కాలానుగుణ ట్రెండ్లు',
        nearbyMandi: 'సమీప మార్కెట్',
        commodityName: 'వస్తువు పేరు',
        quantity: 'పరిమాణం',
        location: 'స్థానం',
        bestPrice: 'ఉత్తమ ధర',
        voiceSearch: 'వాయిస్ సెర్చ్',
    },
    mr: {
        welcomeBack: 'स्वागत आहे',
        selectLanguage: 'तुमची भाषा निवडा',
        speakInYourLanguage: 'तुमच्या भाषेत बोला',
        continue: 'सुरू ठेवा',
        vendor: 'विक्रेता',
        buyer: 'खरेदीदार',
        listCommodity: 'वस्तू सूची',
        browseMandi: 'मंडी ब्राउझ करा',
        aiSuggestedPrice: 'AI सुचविलेली किंमत',
        whyThisPrice: 'ही किंमत का?',
        negotiate: 'चर्चा करा',
        accept: 'स्वीकार',
        counter: 'काउंटर ऑफर',
        marketDemand: 'बाजार मागणी',
        seasonalTrends: 'हंगामी ट्रेंड',
        nearbyMandi: 'जवळील मंडी',
        commodityName: 'वस्तूचे नाव',
        quantity: 'प्रमाण',
        location: 'स्थान',
        bestPrice: 'सर्वोत्तम किंमत',
        voiceSearch: 'व्हॉइस सर्च',
    },
    gu: {
        welcomeBack: 'સ્વાગત છે',
        selectLanguage: 'તમારી ભાષા પસંદ કરો',
        speakInYourLanguage: 'તમારી ભાષામાં બોલો',
        continue: 'ચાલુ રાખો',
        vendor: 'વિક્રેતા',
        buyer: 'ખરીદદાર',
        listCommodity: 'ચીજવસ્તુ સૂચિ',
        browseMandi: 'માંdડી બ્રાઉઝ કરો',
        aiSuggestedPrice: 'AI સૂચવેલ કિંમત',
        whyThisPrice: 'આ કિંમત શા માટે?',
        negotiate: 'વાટાઘાટ કરો',
        accept: 'સ્વીકારો',
        counter: 'કાઉન્ટર ઑફર',
        marketDemand: 'બજાર માંગ',
        seasonalTrends: 'મौસમી વલણો',
        nearbyMandi: 'નજીકની માંડી',
        commodityName: 'ચીજવસ્તુનું નામ',
        quantity: 'જથ્થો',
        location: 'સ્થાન',
        bestPrice: 'શ્રેષ્ઠ કિંમત',
        voiceSearch: 'વૉઇસ સર્ચ',
    },
    en: {
        welcomeBack: 'Welcome Back',
        selectLanguage: 'Select Your Language',
        speakInYourLanguage: 'Speak in your language',
        continue: 'Continue',
        vendor: 'Vendor',
        buyer: 'Buyer',
        listCommodity: 'List Commodity',
        browseMandi: 'Browse Mandi',
        aiSuggestedPrice: 'AI Suggested Price',
        whyThisPrice: 'Why this price?',
        negotiate: 'Negotiate',
        accept: 'Accept',
        counter: 'Counter Offer',
        marketDemand: 'Market Demand',
        seasonalTrends: 'Seasonal Trends',
        nearbyMandi: 'Nearby Mandi',
        commodityName: 'Commodity Name',
        quantity: 'Quantity',
        location: 'Location',
        bestPrice: 'Best Price',
        voiceSearch: 'Voice Search',
    },
};

export function getTranslation(langCode, key) {
    return TRANSLATIONS[langCode]?.[key] || TRANSLATIONS.en[key] || key;
}
